### PR TITLE
added contains function

### PR DESCRIPTION
**Pull request by androidovshchik**
Added an implementation of [contains function](https://developer.android.com/reference/android/content/SharedPreferences#contains(java.lang.String))

### CODE REVIEW

**Review by androidovshchik — COMMENTED** [review]
fix the problem

**Comment by chibatching** [comment]
@androidovshchik Thank you for your PR.

Please add  PR description summary and let me know your purpose.

**Comment by androidovshchik** [comment]
Hi
I wanna just to add an implementation of [this function](https://developer.android.com/reference/android/content/SharedPreferences#contains(java.lang.String)). It's hard to determine without it whether preferences has some key or not.

**Comment by chibatching** [comment]
@androidovshchik 
Sorry for my late reply.

I understood this PR purpose, but I think contains will mislead.
This will check preference key existence against property. And property is always existing.

I prefer to keyExists for the name of this function. 
Please change the name of function and documentation

**Comment by androidovshchik** [comment]
It's not the same. My contains function checks whether key exists in preference file but NOT CLASS

**Comment by chibatching** [comment]
Naming `KotprefModel#contains(property)` looks checking KotprefModel class contains properties passed as param for me.
But actually, your function checks the existence of the preference key in the preference file. I don't prefer this naming.

**Pull request closed without merging**
